-- Seed data for candidate_support_content
INSERT INTO candidate_support_content (content_type, title, content, industry, is_active) VALUES
('interview_guide', 'Technisches Interview vorbereiten', E'## Checkliste für technische Interviews\n\n1. **Algorithmen & Datenstrukturen auffrischen**\n   - Arrays, Listen, Bäume, Graphen\n   - Sortier- und Suchalgorithmen\n   - Big-O Notation verstehen\n\n2. **System Design Grundlagen**\n   - Skalierbarkeit\n   - Datenbank-Design\n   - API-Design\n\n3. **Eigene Projekte erklären können**\n   - Herausforderungen und Lösungen\n   - Technologie-Entscheidungen\n   - Lessons Learned\n\n4. **Fragen zum Tech-Stack vorbereiten**\n   - Aktuelle Trends kennen\n   - Vor- und Nachteile verschiedener Technologien', 'Tech', true),

('interview_guide', 'Behavioral Interview Tipps', E'## STAR-Methode für Verhaltens-Interviews\n\n**S**ituation - Beschreibe den Kontext\n**T**ask - Was war deine Aufgabe?\n**A**ction - Was hast du konkret getan?\n**R**esult - Was war das Ergebnis?\n\n### Häufige Fragen:\n- Erzählen Sie von einer Herausforderung...\n- Wie gehen Sie mit Konflikten um?\n- Beschreiben Sie eine Situation, in der Sie unter Druck standen...\n\n### Tipps:\n- Konkrete Beispiele vorbereiten\n- Zahlen und Fakten nennen\n- Ehrlich bleiben', NULL, true),

('interview_guide', 'Fragen an den Arbeitgeber', E'## Gute Fragen für das Interview\n\n### Zur Position:\n- Wie sieht ein typischer Arbeitstag aus?\n- Was sind die größten Herausforderungen in den ersten 90 Tagen?\n- Wie wird Erfolg in dieser Position gemessen?\n\n### Zum Team:\n- Wie groß ist das Team?\n- Wie ist die Zusammenarbeit organisiert?\n- Welche Tools werden verwendet?\n\n### Zur Firma:\n- Wie sehen die Wachstumspläne aus?\n- Was unterscheidet die Unternehmenskultur?\n- Welche Entwicklungsmöglichkeiten gibt es?', NULL, true),

('salary_benchmark', 'Gehaltsverhandlung Tipps', E'## Erfolgreich über Gehalt verhandeln\n\n### Vorbereitung:\n1. Marktwert recherchieren (Glassdoor, LinkedIn, Kununu)\n2. Eigene Erfolge dokumentieren\n3. Gehaltsrange definieren (Minimum, Ziel, Optimum)\n\n### Im Gespräch:\n- Nie als Erster eine Zahl nennen\n- Gesamtpaket betrachten (Benefits, Bonus, Remote...)\n- Immer sachlich und professionell bleiben\n\n### Formulierungen:\n- "Basierend auf meiner Erfahrung und den Marktdaten liegt meine Gehaltsvorstellung bei..."\n- "Was ist die Gehaltsspanne für diese Position?"', NULL, true),

('confidence_builder', 'Du schaffst das!', E'## Warum du der richtige Kandidat bist\n\n### Denke daran:\n- Du wurdest aus vielen Bewerbern ausgewählt\n- Deine Erfahrung und Fähigkeiten sind gefragt\n- Ein Interview ist ein Gespräch auf Augenhöhe\n\n### Vor dem Interview:\n- Tief durchatmen\n- Power-Pose (2 Minuten)\n- Positive Visualisierung\n\n### Im Interview:\n- Du bist der Experte für deine Erfahrung\n- Fehler sind menschlich - einfach korrigieren\n- Authentisch sein ist der Schlüssel\n\n**Du hast es verdient, hier zu sein!**', NULL, true),

('company_culture', 'Unternehmenskultur verstehen', E'## Was Unternehmenskultur bedeutet\n\n### Aspekte der Kultur:\n- **Arbeitsweise**: Agil, klassisch, hybrid\n- **Kommunikation**: Offen, hierarchisch, dezentral\n- **Work-Life-Balance**: Flexible Zeiten, Remote, Überstunden\n- **Entwicklung**: Weiterbildung, Karrierepfade, Mentoring\n\n### Fragen zum Erkunden:\n- Wie werden Entscheidungen getroffen?\n- Wie wird Feedback gegeben?\n- Wie sieht Teamarbeit aus?\n- Was passiert bei Fehlern?\n\n### Red Flags:\n- Ausweichende Antworten\n- Hohe Fluktuation\n- Negative Bewertungen auf Kununu/Glassdoor', NULL, true);

-- Enable realtime for influence tables
ALTER PUBLICATION supabase_realtime ADD TABLE influence_alerts;
ALTER PUBLICATION supabase_realtime ADD TABLE candidate_behavior;